# Site settings
title: Scott Frees
email: scott.frees@gmail.com
description: > # I'm a freelance software developer and consultant. I specialize in custom application development, workflow automation, and science/engineering data analysis and visualization.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottfrees.com" # the base hostname & protocol for your site
github_username:  freezer333

# Build settings
markdown: kramdown
